[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "E5esXJ8cfHNa9pSTr5nqqEMpQ81tQ2PBmnHiz5UWF7fN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
